- name: variables in ansible
  hosts: mangodb
  vars:
    course: devops #playlevel variables
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "hello world"
  - name: printing using variables
    ansible.builtin.debug:
      msg: "i am learning {{course}}"