- name: variables from files
  hosts: localhost
  vars_files:
  - variables.yaml  #variables from files
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "we are learning {{name}}" 