- name: prompting the variables
  hosts: localhost
  vars_prompt:

  - name: username
    prompt: please enter username
    private: false

  - name: password
    prompt: please enter password

  tasks:
  - name: printing variables from prompt
  ansible.builtin.debug:
   msg: "{{username}} and {{password}}"