- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"
  - name: print exitstatus
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: create a user if not created
    ansible.builtin.user:
      name: roboshop
    when: output.rc !=0